In [1]:
import numpy as np
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

**Modifying the view also modifies the original**

In [2]:
b = a[::2]
b

array([0, 2, 4])

In [3]:
b[1] = -4
b

array([ 0, -4,  4])

In [5]:
a

array([ 0,  1, -4,  3,  4])

**Copying** - Original array is not modified

In [6]:
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
d = c[:3].copy()
d

array([0, 1, 2])

In [11]:
d[2] = 48
d

array([ 0,  1, 48])

In [12]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])