In [1]:
import numpy as np

In [4]:
np.random.seed(20)
a = np.random.randint(25,50,10) # start, end+1, array_size
a

array([28, 40, 34, 45, 36, 47, 32, 27, 25, 47])

In [7]:
# Create a bool mask array to filter out only even nos
a_even = (a % 2 == 0)
a_even

array([ True,  True,  True, False,  True, False,  True, False, False,
       False])

In [8]:
# Use bool array to create new array with only even
a_evens = a[a_even]
a_evens

array([28, 40, 34, 36, 32])

In [9]:
# Array masking to replace a missing value
country = np.array(['France', 'Greece', 'Syria', 'Germany', 'Ukraine', 'Hungary', '', 'Nigeria'])
country

array(['France', 'Greece', 'Syria', 'Germany', 'Ukraine', 'Hungary', '',
       'Nigeria'], dtype='<U7')

In [10]:
# Finding the blank element and replacing it
country[country == ''] = 'Russia'
country

array(['France', 'Greece', 'Syria', 'Germany', 'Ukraine', 'Hungary',
       'Russia', 'Nigeria'], dtype='<U7')

In [11]:
b = 20*np.arange(11,20)
b

array([220, 240, 260, 280, 300, 320, 340, 360, 380])

In [12]:
# Creating a new array by masking out specific indices
c = b[[1,3,4,2,7]] # double sq brackets are necessary, else there will be error
c

array([240, 280, 300, 260, 360])

In [13]:
b[[1,3]] = [50,51] # Assignment with indexing
b

array([220,  50, 260,  51, 300, 320, 340, 360, 380])

**Complex indexing**
Replacing a smaller array from a bigger array by complex indexing

In [15]:
d = np.arange(20)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
# e = np.arange(-19,-10), but in complex way😂
e = np.arange(-11,-20,-1)[::-1]
e

array([-19, -18, -17, -16, -15, -14, -13, -12, -11])

In [19]:
# Replacing indices 0-8 of d with elements of e
d[:9] = e
d

array([-19, -18, -17, -16, -15, -14, -13, -12, -11,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])