**Broadcasting**
Combining arrays having different shape

###### The array 2 will be broadcasted onto array 1

In [4]:
import numpy as np
a = np.ones((5,2), dtype='int')
a

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [5]:
b = np.array([5,2])
b

array([5, 2])

In [7]:
# Add array b to every corresponding element of a
c = a+b
c

array([[6, 3],
       [6, 3],
       [6, 3],
       [6, 3],
       [6, 3]])

In [12]:
d = np.array([[11,22,33]])
e = d.T
print(d,'\n')
print(e)

[[11 22 33]] 

[[11]
 [22]
 [33]]


In [13]:
d+e

array([[22, 33, 44],
       [33, 44, 55],
       [44, 55, 66]])