In [13]:
import numpy as np

ar_1 = np.array([11, 22, 33, 44, 55])
ar_2 = np.array([[10, 20, 30], [40, 50, 60]])
print(ar_1)
print(ar_2)

[11 22 33 44 55]
[[10 20 30]
 [40 50 60]]


Shape of an array

In [2]:
print(ar_1.shape)
print(ar_2.shape)

(5,)
(2, 3)


Dimension of array

In [3]:
ar_1.ndim
ar_2.ndim

2

**Array creation using arange and linspace

In [4]:
ar_1 = np.arange(5)
print(ar_1)

[0 1 2 3 4]


In [5]:
ar_2 = np.arange(1, 10, 2)
print(ar_2)

[1 3 5 7 9]


In [6]:
# Creating array using linspace(start, end, no_of_elements)
ar_3 = np.linspace(0, 0.75, 4)
print(ar_3)

[0.   0.25 0.5  0.75]


**Array creation with special functions

In [7]:
# Array of ones
one = np.ones((2, 3))
print(one)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# Array of zeros
zeros = np.zeros((3, 4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
# Identity matrix
i = np.eye(3, dtype="int")
print(i)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [10]:
# Diagonal matrix
d = np.diag((1, 6, 2, 4))
print(d)

[[1 0 0 0]
 [0 6 0 0]
 [0 0 2 0]
 [0 0 0 4]]


In [11]:
# Uniformly distributed random numbers
np.random.seed(
    200
)  # Given not to produce different random nos each time the code is run
u = np.random.rand(4)
print(u)

[0.94763226 0.22654742 0.59442014 0.42830868]


In [12]:
# Normally distibuted random numbers
# np.random.seed(20)
n = np.random.randn(4)
print(n)

[ 0.71187915 -0.24773829  0.36146623 -0.03294967]


In [14]:
emt = np.empty((4, 3))
emt

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
# Construct an array from a smaller array by repeating it several times
small = np.array([[5, 3], [8, 4]])
rep = np.tile(small, 3)
rep

array([[5, 3, 5, 3, 5, 3],
       [8, 4, 8, 4, 8, 4]])