**Array Shape manipulation**

**np.ravel()** - flattens a nD array to 1D, generates a view of the array

**np.flatten()** - Flattens, but gives a copy of the array

In [9]:
import numpy as np
a = np.array([np.arange(2,7), np.arange(15,20)])
a

array([[ 2,  3,  4,  5,  6],
       [15, 16, 17, 18, 19]])

In [10]:
b = a.ravel()
b

array([ 2,  3,  4,  5,  6, 15, 16, 17, 18, 19])

In [11]:
a.T

array([[ 2, 15],
       [ 3, 16],
       [ 4, 17],
       [ 5, 18],
       [ 6, 19]])

In [12]:
c = np.transpose(a).ravel()
c

array([ 2, 15,  3, 16,  4, 17,  5, 18,  6, 19])

**Reshaping**

Returns a view keeping the underlying array unchanged

In [13]:
d = np.arange(11,26)
e = d.reshape(3,5)
e

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**Resizing**

In [17]:
# array_name.resize() - Resizing the original array
f = np.arange(10,15)
f.resize((8,))
f

array([10, 11, 12, 13, 14,  0,  0,  0])

In [19]:
# array_name.resize() won't allow resizing if there are references
f = np.arange(10,15)
g = f # g references to f
g.resize((8,))
g

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [20]:
# np.resize(array_name) - This returns a new array that can be stored to another
h = np.resize(f, (8,))
h

array([10, 11, 12, 13, 14, 10, 11, 12])

**Adding a new dimension to an array**

In [22]:
# np.newaxis()
i = np.array([21,22,23])
i.shape

(3,)

In [23]:
j = i[: , np.newaxis]
print(j.shape)
print(j)

(3, 1)
[[21]
 [22]
 [23]]
