**Reduction Operations**
Done by either sum() or prod() function

In [2]:
import numpy as np
a = np.arange(2,6)
a.prod() # Axis is not specified -> redn is applied to all elements

120

In [3]:
b = np.array([np.arange(2,6), np.arange(2,6)])
b

array([[2, 3, 4, 5],
       [2, 3, 4, 5]])

In [5]:
# Col wise - multiply every elements in a column and return a 1xn matrix
c = np.prod(b, axis = 0) # axis=0 means col
c

array([ 4,  9, 16, 25])

In [6]:
#row wise
d = np.prod(b, axis = 1) # axis=1 means row wise
d

array([120, 120])

In [7]:
e = np.array([[2,4,6],[1,3,5],[10,11,12]])
e

array([[ 2,  4,  6],
       [ 1,  3,  5],
       [10, 11, 12]])

In [8]:
# Not specifying axis
e.sum()

54

**Statistical Operations**
np.std(), np.mean(), np.median(), np.var() and np.cumsum()

In [14]:
np.random.seed(100)
s1 = np.random.randint(0,10, size=(5,4))
s1

array([[8, 8, 3, 7],
       [7, 0, 4, 2],
       [5, 2, 2, 2],
       [1, 0, 8, 4],
       [0, 9, 6, 2]])

In [15]:
s1.mean()

4.0

In [16]:
np.median(s1)

3.5

In [17]:
# std dev
s1.std()

2.949576240750525

In [22]:
# Variance
s1.var(axis=1) # across rows

array([ 4.25  ,  6.6875,  1.6875,  9.6875, 12.1875])

In [21]:
s1.cumsum()

array([ 8, 16, 19, 26, 33, 33, 37, 39, 44, 46, 48, 50, 51, 51, 59, 63, 63,
       72, 78, 80])

**Logical operations** | 
np.all() : For element wise 'and' all of the elements | 
np.any() : For element wise 'or' all of the elements

In [24]:
np.random.seed(200)
l_1 = np.random.randint(11,20,size=(4,4))
l_1

array([[11, 15, 18, 17],
       [19, 12, 18, 14],
       [12, 18, 16, 19],
       [18, 17, 17, 11]])

In [25]:
np.any(l_1 % 7 == 0)

True

In [28]:
np.all(l_1 < 11)

False