**All operations applied to the the array will be performed element wise**

In [38]:
import numpy as np
a = np.arange(1,10)*4
a

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36])

In [39]:
b = np.arange(1,10)**4
b

array([   1,   16,   81,  256,  625, 1296, 2401, 4096, 6561], dtype=int32)

In [40]:
c = a**0.5
c

array([2.        , 2.82842712, 3.46410162, 4.        , 4.47213595,
       4.89897949, 5.29150262, 5.65685425, 6.        ])

In [41]:
# Addition in an array
d = 1 + np.arange(0,20,2)
d

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [42]:
e = np.arange(0,10)
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
# Array subtraction
f = d - e
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
# Array division
g = e/d
g

array([0.        , 0.33333333, 0.4       , 0.42857143, 0.44444444,
       0.45454545, 0.46153846, 0.46666667, 0.47058824, 0.47368421])

In [45]:
# Array multiplication
h = d*e
h

array([  0,   3,  10,  21,  36,  55,  78, 105, 136, 171])

#### A comparison to show the process time diff b/w array and list
%timeit can be used to print the time required for an operation

In [46]:
sample1 = np.arange(100)
%timeit sample1 ** 3

2.32 µs ± 91.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [47]:
sample2 = list(range(100))
%timeit [i ** 3 for i in sample2]

29.6 µs ± 3.48 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [48]:
sample1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [49]:
print(sample2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


#### Matrix Multiplication

In [53]:
m1 = np.array([[5,5],[5,5]])
m1

m2 = np.array([[7,7],[7,7]])
m2

mvalue = m1.dot(m2) # dot() is used for matrix multiplication
mvalue

array([[70, 70],
       [70, 70]])

#### Comparison operations - done element wise

In [59]:
c1 = np.arange(2,7)
c2 = np.arange(10,5,-1)
c3 = c1 < c2
c3

array([ True,  True,  True,  True, False])

#### Logical operations - done element wise

In [60]:
x = np.array([False, False, True, True])
y = np.array([True, False, True, False])
z = np.logical_and(x,y)
z

array([False, False,  True, False])

**Trigonometric fn - done element wise**

In [63]:
s = np.array([np.pi, np.pi/2])
s1 = np.sin(s)
s1

array([1.2246468e-16, 1.0000000e+00])

In [65]:
# Transpose of a matrix - Can be done by ar_name.T or np.transpose(ar_name)
t1 = np.array([[1,2], [3,4], [5,6]])
print(t1)
t2 = t1.T
print(t2)
t3 = np.transpose(t1)
print(t3)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]
[[1 3 5]
 [2 4 6]]


**Array comparison, array-wise**

In [67]:
arr1 = np.arange(1,7)
arr2 = np.array([1,2,3,4,5,6])
# comparison 1
arr3 = np.array_equal(arr1, arr2)
arr3

True

In [68]:
# 
arr4 = np.all(arr1 == arr2)
arr4

True