In [1]:
import numpy as np

a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

In [2]:
print(a[0])
print(a[-1])

1
5


In [3]:
b = a[::-1]
b

array([5, 4, 3, 2, 1])

**Multidimensional Array indexing

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
b = np.array([np.arange(1, 4), np.arange(4, 7), np.arange(7, 10)])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
a[1][1]

5

In [7]:
a[1][1] = 50
a

array([[ 1,  2,  3],
       [ 4, 50,  6],
       [ 7,  8,  9]])

**Accessing Row or column only

In [8]:
# Row 0
a[0]

array([1, 2, 3])

In [55]:
# Accessing 1st row, and all column values in it
a[1, :]

array([ 4, 50,  6])

In [10]:
# Accessing 2nd column and all row values in it
a[:, 2]

array([3, 6, 9])

In [13]:
c = 2 * np.arange(
    10
)  # create an array of elements from 0-9, and multiply all elements by 2
c

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
d = c[0::2]  # All elements but stepped by 2
d

array([ 0,  4,  8, 12, 16])

In [23]:
e = d[:3]  # 1st 3 elements of 'd'
e

array([0, 4, 8])

In [25]:
f = np.arange(1, 12, 2)
f

array([ 1,  3,  5,  7,  9, 11])

In [27]:
f[:3] = 1  # Replaces the values at indices 0-2 with value 1
f

array([ 1,  1,  1,  7,  9, 11])

In [30]:
f[3:] = np.ones(3)  # Making the remaining elements also 1
f

array([1, 1, 1, 1, 1, 1])

### While slicing multi-dimensional array [ : , : ]
, seperates slicing values of row and column
[row, col1 : col2] = only row'th column is accessed and its col1 to col2 elements
[row: , col1 : col2] = starting from row, all rows are accessed and its col1 to col2

In [36]:
# Creating a 5x5 array
g = np.array(
    [
        np.arange(1, 6),
        np.arange(6, 11),
        np.arange(11, 16),
        np.arange(16, 21),
        np.arange(21, 26),
    ]
)
g

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [57]:
g[0, 3:5]  # Only row0, and its elements from col3 to col4

array([4, 5])

In [58]:
g[3:, 3:]  # All rows starting from 3, and all corresponding cols starting from 3

array([[19, 20],
       [24, 25]])

In [60]:
g[:, 2]  # All values of col2

array([ 3,  8, 13, 18, 23])

In [62]:
g[2::2, ::2]  # row2 to end in steps of 2, and all cols in steps of 2

array([[11, 13, 15],
       [21, 23, 25]])

In [64]:
g[2, 2]  # intersection of row2 and col2

13

In [66]:
g[2][2]  # intersection of row2 and col2

13