In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
ary = np.array([1, 2, 3, 5, 8])
ary = ary + 1
print(ary[1])

3


In [4]:
a = np.array([[1, 2, 3], [0, 1, 4]])
print(a.size)

6


In [5]:
s = pd.Series(np.random.randn(4))
s.ndim

1

In [6]:
s = pd.Series([1, 2, 3, 4, 5], index=["a", "b", "c", "d", "e"])
print(s["a"])

1


In [7]:
print(not (10 < 20) and not (10 > 30))

False


In [8]:
print(np.zeros([1, 9]).reshape(3, 3))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
my_tuple = (1, 2, 3, 4)
my_tuple.append((5, 6, 7))
print(len(my_tuple))

AttributeError: 'tuple' object has no attribute 'append'

In [10]:
n = 0
while n > 0:
    print("Lather")
    print("Rinse")
print("Dry off!")

Dry off!


In [11]:
a = np.array([1, 2, 5, 3])
print(a[a < a.mean()])

[1 2]


In [12]:
print("abcdefcdghcd".split("cd", 2))

['ab', 'ef', 'ghcd']


In [13]:
max([2445, 133, 12454, 123])

12454

In [14]:
p = (2, 3, 4, 5)
print(p[1:-1])

(3, 4)


In [15]:
if (9 < 0) and (0 < -9):
    print("hello")
elif (9 > 0) or False:
    print("good")
else:
    print("bad")

good


In [16]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(A[1])

[4, 5, 6]


In [17]:
def f(x):
    d = 0
    while x >= 1:
        (x, d) = (x / 5, d + 1)
    return d


print(f(4000))

6


In [18]:
example = "helle"
print(example.find("e"))

1


In [19]:
str = "Hello"
print(str[:2])

He


In [20]:
print(list("hello"))

['h', 'e', 'l', 'l', 'o']


In [21]:
d = {"john": 40, "peter": 45}
del d["john"]
print(d)

{'peter': 45}


In [22]:
print(len("banana") * 7)

42


In [23]:
t = (1, 2)
print(2 * t)

(1, 2, 1, 2)


In [24]:
x = 8
if x > 8:
    print(20)
else:
    print(10)

10


In [25]:
a = np.array([1, 2, 5, 3])
a[a < a.mean()]

array([1, 2])